server:
    port: 8081

spring:
    application:
        name: auth-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/authdb

    docker:
        compose:
            enabled: false

jwt:
    secret: L0zCapQbtILtj4aTZqaUP9mbKn7MykRfRern8u1jn8g=
    expiration: 3600000  # 1 hora en milisegundos

logging:
    level:
        org:
            springdoc: DEBUG
            springframework: DEBUG
        root: INFO
        io.swagger.v3: DEBUG