server:
    port: 8081

spring:
    application:
        name: auth-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/authdb

    docker:
        compose:
            enabled: false

jwt:
    secret: YmFzZTY0RW5jb2RlZFJlYWxseVNlY3VyZVNlY3JldEtleQ==
    expiration: 3600000  # 1 hora en milisegundos

logging.level:
    org:
        springdoc: DEBUG
    io.swagger.v3: DEBUG