server:
  port: 8082

spring:
  application:
    name: medical-service

  data:
    mongodb:
      uri: mongodb://mongo-db:27017/medicaldb

jwt:
  secret: YmFzZTY0RW5jb2RlZFJlYWxseVNlY3VyZVNlY3JldEtleQ==
  expiration: 3600000  # 1 hora en milisegundos

logging.level:
  org:
    springdoc: DEBUG
    springframework: DEBUG
  io.swagger.v3: DEBUG